/**
 * @license
 * Copyright 2024 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import * as pathlib from 'path';
import {dedent} from 'ts-dedent';
import {WireitTestRig} from './test-rig.js';

type TestEnviron = {
  rig: WireitTestRig;
  command: string;
  extraScripts?: Record<string, string>;
};

export const injectYarnBerryToRig = async (rig: WireitTestRig) => {
  await rig.write({
    '.yarnrc.yml': `
      nodeLinker: node-modules
      yarnPath: ${pathlib.join(
        process.cwd(),
        'third_party',
        '.yarn',
        'releases',
        'yarn-4.0.1.cjs',
      )}
    `,
  });

  // `yarn.lock` tells `yarn` that this test is meant to be its own workspace
  // root, even though there are higher `package.json` files in the file tree.
  //
  // This is the `yarn.lock` you get if you initialize `yarn` in an empty
  // folder.
  await rig.write({
    'yarn.lock': dedent`
      # This file is generated by running "yarn install" inside your project.
      # Manual changes might be lost - proceed with caution!

      __metadata:
        version: 8
        cacheKey: 10c0

      "root-workspace-0b6124@workspace:.":
        version: 0.0.0-use.local
        resolution: "root-workspace-0b6124@workspace:."
        languageName: unknown
        linkType: soft
    `,
  });
};
